### ISSUE TITLE
Migrate 'master' branch to 'main'

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure-Samples/iot-reliable-edge-relay#5]
We should migrate the "master" branch to a branch called "main" to be in sync with industry and MSFT standards.

**Comment by WilliamBerryiii** [comment]
@aguywithcode - could you make this change?

**Comment by aguywithcode** [comment]
Done...any existing clones will need an update.  But the branch has been renamed.

**Comment by aguywithcode** [comment]
Done...any existing clones will need an update.  But the branch has been renamed.
